name: nsgt-torch

channels:
  - default
  - pytorch
  - conda-forge

dependencies:
  - python>=3.9
  - numpy
  - numba
  - scipy
  - pytorch>=2.0
  - torchaudio
  - tqdm
  - libsndfile
  - ffmpeg
  - pip
  - pip:
    - matplotlib
    - line_profiler
    - memory_profiler
    - "-e ."
